# column transformer
#### ColumnTransformer is a Scikit-learn tool used to apply different preprocessing techniques to different columns of a dataset

| Age | Salary | Gender | City   |
| --: | -----: | ------ | ------ |
|  20 |  30000 | Male   | Jaipur |
|  25 |  50000 | Female | Delhi  |
|  30 |  70000 | Male   | Mumbai |

Here:

Age, Salary → numerical columns
Gender, City → categorical columns

We don't want to apply the same preprocessing to all columns.

# why we use this --> because when we apply the incoding techinque on a perticular col then first we have to seperate that col and apply it same for the other col --> in the end we have to merge it --> it is boring and it take lot of effort

# we can do in incoding without seperating the col --> by the help of Column Transformer

----------

# how to use it

# we will use the ---> sklearn --> we have compose in it and we have to import the columnTransoformer

### from sklearn.compose import columnTranformer

# lets understand the syntex of it:

### columnTranformer()---> 
- first parameter -->contain Name,transformer,column
- second parameter--> remainder -->rest of the numerical col we are having ---> what we can do with numerical col ---> either we can drop it or we can   # passthough --->let it be(it won't we applicable for all the numerical col but it is applicable which are left out)

#### transformation -->15 out of 20 col --> going to use the reminder as drop ---> so it will remove the rest 5 col

#### but if i don't want to remove these 5 col --> i can go with --> remender as passthough

-------

# we will see the tranformer in detail --> because in it there will be all logic

### tansformer as a prameter ---> things transformer is conserned about 
- #### name we provide to the current transformer we are using 
- #### original or exact transformer ---> it can be ordinalEncoder or oneHotencoder or simple imputer
- #### column name ---> on which col you want to apply transformation

### these above step was for the input col

# what we will do for the output col --->for handeling the output data we go with labelEncoder

--------
-------

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [4]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [5]:
df.isnull().sum()

Age          0
Job          0
Marital      0
Education    0
Default      0
Balance      0
Housing      0
Loan         0
contact      0
Day          0
Month        0
Duration     0
Campaign     0
Pdays        0
Previous     0
poutcome     0
TARGET       0
dtype: int64

In [7]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

In [12]:
transformer=ColumnTransformer(transformers=[('tr1',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']]),['Education']),('tr2',OneHotEncoder(),['Job','Marital','Default','Housing','Loan','contact','Month','poutcome'])],remainder='passthrough')

In [13]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1',
                                 OrdinalEncoder(categories=[['unknown',
                                                             'primary',
                                                             'secondary',
                                                             'tertiary']]),
                                 ['Education']),
                                ('tr2', OneHotEncoder(),
                                 ['Job', 'Marital', 'Default', 'Housing',
                                  'Loan', 'contact', 'Month', 'poutcome'])])

In [14]:
X=df.iloc[:,:-1]

In [15]:
X

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [16]:
Y=df['TARGET']

In [18]:
Y

0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: TARGET, Length: 45211, dtype: str

In [20]:
X=transformer.fit_transform(X)

In [21]:
X

array([[  3.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       ...,
       [  2.,   0.,   0., ...,   5., 184.,   3.],
       [  2.,   0.,   1., ...,   4.,  -1.,   0.],
       [  2.,   0.,   0., ...,   2., 188.,  11.]], shape=(45211, 48))

In [25]:
le=LabelEncoder()
Y=le.fit_transform(Y)

In [26]:
Y

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))