# data geathering for json data

In [1]:
import pandas as pd

# how to read the json content --> read_json('path_name')

In [2]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

# how to read the json content from web URL

In [3]:
pd.read_json('https://jsonplaceholder.typicode.com/posts')

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

# XAMPP --> it is a software install in our laptop locally by it we will be able to access over mySQL database if we want to work with SQL data then we use this software

# geathering the SQL data and then need to apply some analysis of want to build on it --> use the liberary --> mysql.connecter 

#### funcation which can help us with connecting with out database --> connect()
#### parameter -->host-->server --> localhost ,
#### user--> username,
#### password --> enter the password,
#### database --> database name

# if i want to read content form it then we will use the below function

#### read_sql_query()--> 'sql query' , database connection variable

In [4]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in d:\genai\Machine learning\.venv\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import mysql.connector

In [9]:
data=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [12]:
df=pd.read_sql_query('select * from city',data)

C:\Users\hites\AppData\Local\Temp\ipykernel_2556\947231853.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query('select * from city',data)

In [13]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [15]:
pd.read_sql_query('select * from city where population>1000000',data)

C:\Users\hites\AppData\Local\Temp\ipykernel_2556\3942298085.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from city where population>1000000',data)

       ID          Name CountryCode          District  Population
0       1         Kabul         AFG             Kabol     1780000
1      35         Alger         DZA             Alger     2168000
2      56        Luanda         AGO            Luanda     2022000
3      69  Buenos Aires         ARG  Distrito Federal     2982146
4      70    La Matanza         ARG      Buenos Aires     1266461
..    ...           ...         ...               ...         ...
232  3798       Phoenix         USA           Arizona     1321045
233  3799     San Diego         USA        California     1223400
234  3800        Dallas         USA             Texas     1188580
235  3801   San Antonio         USA             Texas     1144646
236  4068        Harare         ZWE            Harare     1410000

[237 rows x 5 columns]

In [17]:
ind=pd.read_sql_query('select * from city where CountryCode like "IND"',data)

C:\Users\hites\AppData\Local\Temp\ipykernel_2556\1513916673.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ind=pd.read_sql_query('select * from city where CountryCode like "IND"',data)

In [18]:
ind

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [ ]:
pd.read_sql_query('select * from Country',data)

C:\Users\hites\AppData\Local\Temp\ipykernel_2556\2583526144.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from Country',data)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [20]:
pd.read_sql_query('select * from Country where LifeExpectancy>80',data)

C:\Users\hites\AppData\Local\Temp\ipykernel_2556\1719163561.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from Country where LifeExpectancy>80',data)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
1,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532,JP
2,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454,MO
3,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208,SG
4,SMR,San Marino,Europe,Southern Europe,61.0,885.0,27000,81.1,510.0,NaN,San Marino,Republic,NaN,3171,SM